server:
  port: 8990
spring:
  application:
    name: GATEWAY
  cloud:
    nacos:
      server-addr: 192.168.80.128:8848
    gateway:
      routes:
        - id: users_route
          uri: lb://USERS
          predicates:
            - Path=/invoke

        - id: product_route
          uri: lb://PRODUCTS
          predicates:
            - Path=/product
